export const path = {
  root: `/`,
  main: '/main',
  signUp: `/signup`,
  logIn: `/login`,
  book: `/book/:bookId`,
  bookList: `/books/:memberId`,
  diary: `/diary/:diaryId`,
  editDiary: `/editdiary/:diaryId`,
  makeBook: `/makebook`,
  editBook: `/editbook/:bookId`,
  writeDiary: `/writediary`,
  userpage: `/user/:memberId`,
  people: `/people`,
  theme: '/theme',
};
